### ISSUE TITLE
miniogre run fails on RT-DETR

### ISSUE THREAD

**Issue by TUMAAA** [ogre-run/miniogre#25]
After cloning https://github.com/lyuwenyu/RT-DETR miniogre fails to run with the error shown below
![image](https://github.com/user-attachments/assets/c967563d-02ae-433b-898d-6f039ff5881e)
Attached is the full log

**Comment by wilderlopes** [comment]
Apparently the full log wasn't attached to the previous message.
I am working on reproducing the error.

**Comment by wilderlopes** [comment]
Fix provided in new release v0.10.2: https://github.com/ogre-run/miniogre/releases/tag/v0.10.2

Install v0.10.2 via pip or pipx:

`pip install miniogre`

`pipx install miniogre`
