### ISSUE TITLE
some commands inside the produced ogre_dir/bashrc file are malformed

### ISSUE THREAD

**Issue by TUMAAA** [ogre-run/miniogre#27]
![image](https://github.com/user-attachments/assets/acb89adf-0d32-4bbd-bfe4-b8ec1bc37197)
It appears some commands are malformed. Or how else to interpret the indentation?

**Comment by wilderlopes** [comment]
Fixed by https://github.com/ogre-run/miniogre/commit/af781c514c9a4e8c03aacf3583d674c5545b4e52
